[package]
name = "tokio_chat_common"
version = "0.1.0"
authors = ["Xavier Lange <xrlange@tureus.com>"]
build = "build.rs"

[build-dependencies]
serde_codegen = "0.8"

[dependencies]
serde = "*"
serde_json = "0.8"
